pipeline {
    agent any
    stages {
        stage('Build Application') {
            steps {
                sh '/opt/app/apache-maven/bin/mvn -f java-tomcat-sample/pom.xml clean package'
            }
            post {
                success {
                    echo "Now Archiving the Artifacts...."
                    archiveArtifacts artifacts: '**/*.war'
                }
            }
        }
        stage('Deploy in Staging Environment'){
            steps{
                build job: '5th_SampleJob'

            }
            
        }
        
	stage('Upgrading Production Repository'){
	    steps{
		echo "Pushing code to the acme-prd branch"
		sh 'java-tomcat-sample/push2prod.sh'
		}	
	}

	stage('Deploy to Production'){
            steps{
                timeout(time:5, unit:'DAYS'){
                    input message:'Approve PRODUCTION Deployment?'
                }
                build job: '7th_SampleJob'
            }
        }
    }
}
