pipeline {
    agent any
    stages {
        stage('Build Application') {
            steps {
                sh '''
                #!/bash
                export JKS_HOME=/opt/app/jenkins-ci
                export MVN_HOME=/opt/app/apache-maven
                export PATH=$JAVA_HOME/bin:$JKS_HOME:$MVN_HOME/bin:/opt/app/apache-groovy/bin:$PATH                
                'mvn -f java-tomcat-sample/pom.xml clean package'
                '''
            }
            post {
                success {
                    echo "Now Archiving the Artifacts...."
                    archiveArtifacts artifacts: '**/*.war'
                }
            }
        }
        stage('Deploy in Staging Environment'){
            steps{
                build job: '5th_SampleJob'

            }
            
        }
        stage('Deploy to Production'){
            steps{
                timeout(time:5, unit:'DAYS'){
                    input message:'Approve PRODUCTION Deployment?'
                }
                build job: '6th_SampleJob'
            }
        }
    }
}
